config/routes.rb
HunterPreyApp::Application.routes.draw do
  resources :moves

  resources :turns

  resources :games

  devise_for :players
  
  root :to => 'home#index'
  resources :players
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_many :game_players
	has_many :players, :through => :game_players
	has_many :turns

	validates :name, :uniqueness => {:case_sensitive => false}, presence: true
end

app/models/game_player.rb
class GamePlayer < ActiveRecord::Base
	belongs_to :player
	belongs_to :game
end

app/models/move.rb
class Move < ActiveRecord::Base
	has_one :player
	has_one :turn
end

app/models/player.rb
class Player < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable

  validates :username, uniqueness: true, presence: true, :case_sensitive => false

  has_many :game_players
  has_many :games, :through => :game_players
  has_one :move
end

app/models/turn.rb
class Turn < ActiveRecord::Base
	has_one :game
	has_many :moves
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_player!

  def devise_parameter_sanitizer
    if resource_class == Player
      Player::ParameterSanitizer.new(Player, :player, params)
    else
      super
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.creator_id = current_player.id
    
    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render action: 'show', status: :created, location: @game }
      else
        format.html { render action: 'new' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		
	end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)
    @move.player_id = current_player.id
    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render action: 'show', status: :created, location: @move }
      else
        format.html { render action: 'new' }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
      params[:move]
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  	@players = Player.all
  end

  def show
  	@player = Player.find(params[:id])
  end
end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :set_turn, only: [:show, :edit, :update, :destroy]

  # GET /turns
  # GET /turns.json
  def index
    @turns = Turn.all
  end

  # GET /turns/1
  # GET /turns/1.json
  def show
  end

  # GET /turns/new
  def new
    @turn = Turn.new
  end

  # GET /turns/1/edit
  def edit
  end

  # POST /turns
  # POST /turns.json
  def create
    @turn = Turn.new(turn_params)

    respond_to do |format|
      if @turn.save
        format.html { redirect_to @turn, notice: 'Turn was successfully created.' }
        format.json { render action: 'show', status: :created, location: @turn }
      else
        format.html { render action: 'new' }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /turns/1
  # PATCH/PUT /turns/1.json
  def update
    respond_to do |format|
      if @turn.update(turn_params)
        format.html { redirect_to @turn, notice: 'Turn was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @turn.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /turns/1
  # DELETE /turns/1.json
  def destroy
    @turn.destroy
    respond_to do |format|
      format.html { redirect_to turns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_turn
      @turn = Turn.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def turn_params
      params[:turn]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <% if ((game.players.include?(current_player)) or (game.creator_id == current_player.id)) %>
        <tr>
          <td><%= game.name %> <%= (Player.find(game.creator_id)).username %></td>
          <td><%= link_to 'Show', game %></td>
          <% if game.creator_id == current_player.id %>
            <td><%= link_to 'Edit', edit_game_path(game) %></td>
            <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>
<p>
	<strong>Created by:</strong>
	<%= Player.find(@game.creator_id).username %>
</p>
<p>
	<strong>Players:</strong>
	<% if @game.players.size == 0 %>
		<p> No players for this game. </p>
	<% else %>
		<% @game.players.each do |p| %>
			<%= p.username %>
		<% end %>
	<% end %>
</p>

<p>
	<strong>Turns:</strong>
	<% if @game.turns.size == 0 %>
		<p> No turns for this game. </p>
	<% else %>
		<% @game.turns.each do |turn| %>
			<%= link_to 'Show', turn %>
		<% end %>
	<% end %>
	<%= @game.turns.size %>
</p>

<% if @game.creator_id == current_player.id %>
<%= link_to 'Edit', edit_game_path(@game) %> |
<% end %>
<%= link_to 'Back', games_path %>

app/views/home/index.html.erb
Soon, we'll add links here.

Like this one.

<%= link_to 'Games', games_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Hunter/Prey", root_path, :class=> "navbar-brand" %>
  </div>

  <div class="collapse navbar-collapse navbar-ex1-collapse">
  	<ul class="nav navbar-nav">
  		<% if player_signed_in? %>
			<li>
				<%= link_to 'Logout', destroy_player_session_path, :method=>'delete' %>
			</li>
		<% else %>
			<li>
				<%= link_to 'Login', new_player_session_path %>
			</li>
		<% end %>
		<% if player_signed_in? %>
			<li>
				<%= link_to 'Edit Account', edit_player_registration_path %>
			</li>
		<% else %>
			<li>
				<%= link_to 'Sign up', new_player_registration_path %>
			</li>
		<% end %>
  	</ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Hunter-Prey" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Hunter-Prey" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <%= yield %>
      <footer>
      </footer>
    </div> <!--! end of #container -->
  </body>
</html>

app/views/moves/_form.html.erb
<%= form_for(@move) do |f| %>
  <% if @move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@move.errors.count, "error") %> prohibited this move from being saved:</h2>

      <ul>
      <% @move.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing move</h1>

<%= render 'form' %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<h1>Listing moves for <%= current_player.username %></h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Turn</th>
      <th>Link</th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <% if move.player_id == current_player.id %>
        <td><%= Game.find(Turn.find(move.turn_id).game_id).name %></td>
        <td><%= Turn.find(move.turn_id).id %></td>
        <td><%= link_to 'Show', move %></td>
        <% end %>
        <!--<td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Move', new_move_path %> -->  

app/views/moves/new.html.erb
<h1>New move</h1>

<%= render 'form' %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>

app/views/players/index.html.erb
<ul class="users">
  <% @players.each do |player| %>
    <li>
      <%= link_to player.username, player %> signed up <%= player.created_at.to_date %>
    </li>
  <% end %>
</ul>

app/views/players/show.html.erb
<h3>User</h3>
<p>User: <%= @player.name %></p>
<p>Email: <%= @player.email if @player.email %></p>

app/views/turns/_form.html.erb
<%= form_for(@turn) do |f| %>
  <% if @turn.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@turn.errors.count, "error") %> prohibited this turn from being saved:</h2>

      <ul>
      <% @turn.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/turns/edit.html.erb
<h1>Editing turn</h1>

<%= render 'form' %>

<%= link_to 'Show', @turn %> |
<%= link_to 'Back', turns_path %>

app/views/turns/index.html.erb
<h1>Listing turns</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @turns.each do |turn| %>
      <tr>
        <td><%= link_to 'Show', turn %></td>
        <!--<td><%= link_to 'Edit', edit_turn_path(turn) %></td>
        <td><%= link_to 'Destroy', turn, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!--<%= link_to 'New Turn', new_turn_path %> -->

app/views/turns/new.html.erb
<h1>New turn</h1>

<%= render 'form' %>

<%= link_to 'Back', turns_path %>

app/views/turns/show.html.erb
<p id="notice"><%= notice %></p>

<%= Game.find(@turn.game_id).name %>
<% if @turn.moves.size == 0 %>
	<p> No moves for this game </p>
<% else %>
	<p> These players have moved: </p>
	<% @turn.moves.each do |move| %>
		<%= Player.find(move.player_id).username %>
	<% end %>
<% end %>

<% plmove = @turn.moves.find { |move| move.player_id == current_player.id } %>
<% if plmove.nil? %>
	<p> You have not made a move for this game yet. 
		<%= link_to 'Add Move', Move.create(:player_id => current_player.id, :turn_id => @turn.id) %></p>
<% end %>

<% if Game.find(@turn.game_id).creator_id == current_player.id %>
	<%= link_to 'Edit', edit_turn_path(@turn) %> |
<% end %>
<%= link_to 'Back', turns_path %>